RonnyChiang/twitter-api-2020

migrations/20190115071421-create-user.js, models/followship.js, models/like.js, models/reply.js, models/tweet.js, models/user.js
=> feat: ser database

app.js, config/passport.js, controllers/user-controller.js, middleware/error-handler.js, package-lock.json, package.json, routes/index.js, services/user-services.js
=> feat: add signup function & error message

services/user-services.js
1. 修正資料create
2. 刪除後端密碼重複確認檢查
=> fix: fix signup function

.env.example, app.js, controllers/user-controller.js, middleware/api-auth.js, package-lock.json, package.json, routes/index.js, services/user-services.js
補齊了api-auth的內容 並加上了sign in function
=> fill up Auth and create signIn function

app.js, config/passport.js, controllers/tweet-controller.js, middleware/api-auth.js, routes/index.js, services/tweet-services.js, services/user-services.js
=> Get tweets

config/passport.js, controllers/admin-controller.js, middleware/api-auth.js, routes/index.js, services/admin-services.js, services/user-services.js
=> adminLogin function

controllers/tweet-controller.js, models/tweet.js, routes/index.js, services/tweet-services.js, test/requests/tweet.spec.js
=> feat: add postTweets api

controllers/admin-controller.js, routes/index.js, services/admin-services.js
=> admin get Tweets function

controllers/admin-controller.js, routes/index.js, services/admin-services.js
=> admin delete tweet function

controllers/reply-controller.js, routes/index.js, services/reply-services.js
新增 POST/api/tweets/:tid/replies 新增回覆 api  並通過測試(47:12)
=> feat: POST-reply api

controllers/admin-controller.js, models/index.js, package.json, routes/index.js, seeders/20220217142541-users-seed-file.js, services/admin-services.js, services/user-services.js
=> admin get users function

app.js, controllers/tweet-controller.js, middleware/api-auth.js, routes/admin.js, routes/followship.js, routes/index.js, routes/tweet.js, routes/user.js, services/tweet-services.js
重新整理路由
測試檔都有pass
由於測試檔沒有給user或admin的 role 
所以authenticatedUser 跟 authenticatedAdmin條件有小改
postman測試也都正常
=> Route rebuild

controllers/tweet-controller.js, routes/index.js, services/tweet-services.js
測試更改description成功
再跑一次測試檔  一樣all pass
=> edit Tweet description function

app.js, helpers/file-helpers.js, package-lock.json, package.json, services/user-services.js
1. 修正imgur 上傳 502 bug 
2. 移除不需要的code
3. 重新測試仍完全通過
=> fix: fix putUser imgur func and delete unuse code

services/user-services.js
=> fix: fix errormessage

app.js, middleware/error-handler.js, package-lock.json, package.json
=> feat: Cors

middleware/error-handler.js
為配合前端開發所需，修改error status code 為200 並通過測試
=> change status code

config/passport.js
=> fix: fix to pass online test

services/user-services.js
=> feat: add some isFollowed &isSelf

services/user-services.js
修正getUserReplies api to nest 並通過測試
=> fix: fix getUserReplies to nest

services/reply-services.js
=> fix getReplies to nest

seeders/20220218160821-replies-seed-files.js, services/followship-services.js, services/user-services.js
1. 修正post/delete follow api. 回傳followship改變後的user資訊，以便即時更新追蹤數
2. 修正get following/follower 相關資訊
3. 測試沒有問題
4. 另修正種子資料 reply資料形式
=> Fix:followship api

services/admin-services.js, services/user-services.js
=> fix: fix message  to userstory

README.md, app.js
=> fix clean code
